name: IaC-CD-dev $(Rev:.r) - $(Date:yyyy-MM-dd)
trigger:
  branches:
    include:
    - main
    - prod
    - dev
  paths:
    include:
    - src/01-iac/*
variables:
  - group: dbc-pi-vg-dev-01
pool:
  vmImage: 'ubuntu-latest'
stages:
  - template: templates/IaC-CD-Stages-Template.yaml
    parameters:
      prefix: '$(prefix)'
      azureServiceConnectionName: 'azure-devops-sc'
      environmentName: 'dev'
      path: 'src/01-iac'
      varFile: 'src/01-iac/vars_dev.tfvars'
      publishOutput: true
      UtilResourceGroupName: 'rg-tfstate'